'use client';
import { Header } from '@/components/header';
import { useCart } from '@/lib/cart';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Minus, Plus, Trash2, Loader2, ShieldCheck, Cog } from 'lucide-react';
const labels:Record<string,string>={email:'E-mailadres',minecraft_username:'Minecraft gebruikersnaam',minecraft_uuid:'Minecraft UUID',discord_id:'Discord ID',steam_id:'Steam ID',epic_id:'Epic Games ID',eos_id:'Epic Online Services ID',fivem_citizen_id:'FiveM Citizen ID',ingame_username:'In-game gebruikersnaam',rust_username:'Rust gebruikersnaam',username:'Gebruikersnaam'};
const label=(key:string)=>labels[key]||key.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
export default function Cart(){
 const {items,setQty,remove,total}=useCart();const [store,setStore]=useState<number|null>(null);const [identifiers,setIdentifiers]=useState<string[]>([]);const [values,setValues]=useState<Record<string,string>>({email:''});const [loading,setLoading]=useState(false);const [loadingIds,setLoadingIds]=useState(false);const [error,setError]=useState('');const ids=useMemo(()=>Array.from(new Set(['email',...identifiers])),[identifiers]);
 useEffect(()=>{fetch('/api/store').then(r=>r.json()).then(d=>setStore(d.id||null)).catch(()=>{});},[]);
 useEffect(()=>{if(!store||!items.length)return;setLoadingIds(true);fetch(`/api/checkout/identifiers?store=${store}&products=${encodeURIComponent(JSON.stringify(items.map(i=>i.product.id)))}`).then(r=>r.json()).then(d=>setIdentifiers(Array.isArray(d.identifiers)?d.identifiers:[])).catch(()=>setIdentifiers([])).finally(()=>setLoadingIds(false));},[store,items]);
 const checkout=async()=>{setError('');if(!store)return setError('De winkel kon niet worden geladen.');if(!values.email?.trim())return setError('Vul je e-mailadres in.');if(ids.some(id=>id!=='email'&&!values[id]?.trim()))return setError('Vul alle vereiste spelersgegevens in.');setLoading(true);try{const res=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store,products:items.map(i=>({product_id:i.product.id,type:i.purchaseMode==='subscribe'?'subscribe':'addtocart',quantity:i.quantity,server_selection:i.serverSelection,custom_fields:i.customFields||{}})),user:Object.fromEntries(ids.map(id=>[id,values[id]?.trim()||''])),redirect_success_checkout:`${location.origin}/checkout/success`,redirect_canceled_checkout:`${location.origin}/checkout/canceled`,redirect_pending_checkout:`${location.origin}/checkout/pending`})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Checkout mislukt');location.href=data.url;}catch(e){setError(e instanceof Error?e.message:'Checkout mislukt');setLoading(false)}};
 return <main><Header/><div className="cart-page"><span className="eyebrow">JOUW AANKOOP</span><h1 className="shop-title">Afrekenen bij het <em>Emporium</em></h1>{!items.length?<div className="empty"><Cog className="empty-gear" size={54}/><p>Je aankoop is nog leeg.</p><Link className="brass-button" href="/shop">NAAR HET EMPORIUM</Link></div>:<><div className="cart-list">{items.map(i=><div className="cart-row" key={`${i.product.id}-${i.purchaseMode||'once'}-${i.serverSelection||0}`}>{i.product.image?<img src={i.product.image} alt={i.product.name}/>:<div className="cart-thumb">⚙</div>}<div className="grow"><b>{i.product.name}</b><div className="muted-small">€ {i.product.price.toFixed(2).replace('.',',')} per stuk{i.purchaseMode==='subscribe'?' · Abonnement':' · Eenmalig'}{i.serverSelection?` · Server ${i.serverSelection}`:''}</div></div><div className="qty"><button onClick={()=>setQty(i.product.id,i.quantity-1)} aria-label="Verminder"><Minus size={14}/></button><span>{i.quantity}</span><button onClick={()=>setQty(i.product.id,i.quantity+1)} aria-label="Verhoog"><Plus size={14}/></button></div><button className="remove-btn" onClick={()=>remove(i.product.id)} aria-label="Verwijder"><Trash2 size={16}/></button></div>)}</div><div className="checkout"><div className="checkout-head"><div><span className="eyebrow"><ShieldCheck size={14}/> VEILIG AFREKENEN</span><h2>Afrekenen bij het Emporium</h2></div><span className="tip-badge">SECURE</span></div><p className="checkout-intro">We bepalen automatisch welke identificatie jouw aankoop nodig heeft.</p>{loadingIds?<div className="loading-line"><Loader2 className="spin" size={16}/> Vereiste identificatievelden worden gecontroleerd...</div>:ids.map(id=><label key={id}>{label(id)}<input value={values[id]||''} onChange={e=>setValues(v=>({...v,[id]:e.target.value}))} placeholder={id==='email'?'jij@example.com':`Jouw ${label(id)}`} required={id==='email'||identifiers.includes(id)}/></label>)}{error&&<p className="checkout-error">{error}</p>}<div className="total"><span>Totaal</span><strong>€ {total().toFixed(2).replace('.',',')}</strong></div><button className="brass-button checkout-button" onClick={checkout} disabled={loading}>{loading?<><Loader2 className="spin" size={17}/> BETALING WORDT GESTART...</>:<>DOOR NAAR BETALING <span>→</span></>}</button></div></>}</div></main>
}