'use client';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight, ShieldCheck, Zap, HeartHandshake, Package, Cpu } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Header } from '@/components/header';
import { ProductCard } from '@/components/product-card';
import type { Product } from '@/lib/types';

export default function Home(){ const [products,setProducts]=useState<Product[]>([]); const [online,setOnline]=useState(true); useEffect(()=>{fetch('/api/products').then(r=>r.json()).then(d=>setProducts(d.products||[])).catch(()=>setOnline(false));},[]); return <main><Header/><section className="hero"><div className="steam steam-a"/><div className="steam steam-b"/><div className="hero-gears">⚙</div><motion.div className="hero-copy" initial={{opacity:0,x:-50}} animate={{opacity:1,x:0}} transition={{duration:.8}}><div className="eyebrow"><Cpu size={15}/> BOUW • ONTDEK • OVERLEEF</div><h1>Ontdek de Wereld van<br/><em>Machtige Machines</em></h1><p>Betreed Steampunk SMP. Verzamel krachtige upgrades, unieke cosmetics en exclusieve items voor jouw avontuur.</p><Link className="brass-button" href="/shop">BEKIJK DE SHOP <ArrowRight size={18}/></Link></motion.div><div className="hero-art"><div className="city"><div className="tower t1"/><div className="tower t2"/><div className="tower t3"/><div className="airship">◈</div></div></div><div className="status"><span className={online?'dot':''}/><div><small>SERVER STATUS</small><b>{online?'ONLINE':'OFFLINE'}</b><span>PLAY.STEAMPUNKSMP.NL</span></div></div></section><section className="benefits">{[[ShieldCheck,'VEILIGE BETALINGEN','Via Tip4Serv'],[Zap,'DIRECTE LEVERING','In-game na betaling'],[HeartHandshake,'ONDERSTEUN DE SMP','Help de community'],[Package,'EXCLUSIEVE ITEMS','Alleen hier verkrijgbaar']].map(([Icon,title,text],i)=><motion.div key={i} initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><Icon/><div><b>{title as string}</b><span>{text as string}</span></div></motion.div>)}</section><section className="section"><div className="section-head"><div><span className="eyebrow">UITGEKOZEN DOOR DE COMMUNITY</span><h2>Populaire Producten</h2></div><Link href="/shop">BEKIJK ALLE PRODUCTEN <ArrowRight size={16}/></Link></div><div className="products">{products.length?products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>):[1,2,3,4].map(i=><div className="product-card skeleton" key={i}/>)}</div></section><section className="machine-banner"><div><span className="eyebrow">STEAM POWERED COMMUNITY</span><h2>Jouw avontuur.<br/><em>Jouw machine.</em></h2><p>Maak deel uit van een wereld waarin technologie en Minecraft samenkomen.</p><Link href="/shop" className="text-link">ONTDEK MEER <ArrowRight size={16}/></Link></div><div className="big-gear">⚙</div></section><footer><div className="footer-brand">STEAMPUNK <span>SMP</span></div><p>Ontdek de Wereld van Machtige Machines.</p><span>© {new Date().getFullYear()} Steampunk SMP</span></footer></main>}